# Generated by Django 5.0 on 2024-01-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commment',
            new_name='Comment',
        ),
    ]
